- name: Nginx/Keepalived | Install specific distro packages
  apt:
    name: "{{ distro_packages }}"
    state: present
    update_cache: yes

- name: Nginx/Keepalived | Drop keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Nginx/Keepalived | Drop nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- meta: flush_handlers

- name: Nginx/Keepalived | Enable Keepalived unit
  systemd:
    name: keepalived.service
    state: started
    enabled: yes

- name: Nginx/Keepalived | Enable Nginx unit
  systemd:
    name: nginx.service
    state: started
    enabled: yes
